# Generated by Django 3.0 on 2020-01-06 13:30

import accounts.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='barth_date',
            field=models.DateTimeField(null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[(0, '男性'), (1, '女性')], max_length=3, null=True, validators=[accounts.validate.valid_gender], verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_child_num',
            field=models.IntegerField(default=1, verbose_name='子供の数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hobby',
            field=models.TextField(blank=True, null=True, verbose_name='趣味'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nick_name',
            field=models.CharField(default='jack/peter/mike/etc..', max_length=100, verbose_name='ニックネーム'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(choices=[(0, '会社員'), (1, '専業主婦'), (2, '学生'), (3, 'その他')], max_length=10, null=True, validators=[accounts.validate.valid_occupation], verbose_name='職業'),
        ),
    ]
