# Generated by Django 3.0 on 2020-01-07 11:58

import accounts.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200107_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(0, '男性'), (1, '女性')], max_length=3, null=True, validators=[accounts.validate.valid_gender], verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.IntegerField(choices=[(0, '会社員'), (1, '専業主婦'), (2, '学生'), (3, 'その他')], max_length=10, null=True, validators=[accounts.validate.valid_occupation], verbose_name='職業'),
        ),
    ]
