# Generated by Django 3.0 on 2020-01-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200107_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='barth_date',
            field=models.DateField(null=True, verbose_name='生年月日'),
        ),
    ]
