# Generated by Django 3.0 on 2019-12-30 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schedule.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0_a', models.IntegerField(verbose_name='当日午前')),
                ('d0_b', models.IntegerField(verbose_name='当日正午')),
                ('d0_c', models.IntegerField(verbose_name='当日午後')),
                ('d1_a', models.IntegerField(verbose_name='1日後の午前')),
                ('d1_b', models.IntegerField(verbose_name='1日後の正午')),
                ('d1_c', models.IntegerField(verbose_name='1日後の午後')),
                ('d2_a', models.IntegerField(verbose_name='2日後の午前')),
                ('d2_b', models.IntegerField(verbose_name='2日後の正午')),
                ('d2_c', models.IntegerField(verbose_name='2日後の午後')),
                ('d3_a', models.IntegerField(verbose_name='3日後の午前')),
                ('d3_b', models.IntegerField(verbose_name='3日後の正午')),
                ('d3_c', models.IntegerField(verbose_name='3日後の午後')),
                ('d4_a', models.IntegerField(verbose_name='4日後の午前')),
                ('d4_b', models.IntegerField(verbose_name='4日後の正午')),
                ('d4_c', models.IntegerField(verbose_name='4日後の午後')),
                ('d5_a', models.IntegerField(verbose_name='5日後の午前')),
                ('d5_b', models.IntegerField(verbose_name='5日後の正午')),
                ('d5_c', models.IntegerField(verbose_name='5日後の午後')),
                ('d6_a', models.IntegerField(verbose_name='6日後の午前')),
                ('d6_b', models.IntegerField(verbose_name='6日後の正午')),
                ('d6_c', models.IntegerField(verbose_name='6日後の午後')),
                ('d7_a', models.IntegerField(verbose_name='7日後の午前')),
                ('d7_b', models.IntegerField(verbose_name='7日後の正午')),
                ('d7_c', models.IntegerField(verbose_name='7日後の午後')),
                ('d8_a', models.IntegerField(verbose_name='8日後の午前')),
                ('d8_b', models.IntegerField(verbose_name='8日後の正午')),
                ('d8_c', models.IntegerField(verbose_name='8日後の午後')),
                ('d9_a', models.IntegerField(verbose_name='9日後の午前')),
                ('d9_b', models.IntegerField(verbose_name='9日後の正午')),
                ('d9_c', models.IntegerField(verbose_name='9日後の午後')),
                ('d10_a', models.IntegerField(verbose_name='10日後の午前')),
                ('d10_b', models.IntegerField(verbose_name='10日後の正午')),
                ('d10_c', models.IntegerField(verbose_name='10日後の午後')),
                ('d11_a', models.IntegerField(verbose_name='11日後の午前')),
                ('d11_b', models.IntegerField(verbose_name='11日後の正午')),
                ('d11_c', models.IntegerField(verbose_name='11日後の午後')),
                ('d12_a', models.IntegerField(verbose_name='12日後の午前')),
                ('d12_b', models.IntegerField(verbose_name='12日後の正午')),
                ('d12_c', models.IntegerField(verbose_name='12日後の午後')),
                ('d13_a', models.IntegerField(verbose_name='13日後の午前')),
                ('d13_b', models.IntegerField(verbose_name='13日後の正午')),
                ('d13_c', models.IntegerField(verbose_name='13日後の午後')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=3, validators=[schedule.validate.valid_gender], verbose_name='性別')),
                ('barth_date', models.DateTimeField(null=True, verbose_name='生年月日')),
                ('occupation', models.CharField(max_length=10, validators=[schedule.validate.valid_occupation], verbose_name='職業')),
                ('hobby', models.TextField(blank=True, null=True, verbose_name='趣味')),
                ('has_child_num', models.IntegerField(verbose_name='子供の数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barth_date', models.DateTimeField(null=True, verbose_name='パートナーの生年月日')),
                ('occupation', models.CharField(max_length=5, validators=[schedule.validate.valid_occupation], verbose_name='パートナーの職業')),
                ('hobby', models.TextField(blank=True, null=True, verbose_name='パートナーの趣味')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Partner',
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='友人')),
                ('group', models.CharField(max_length=100, verbose_name='グループ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Friends',
            },
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='子供の名前')),
                ('gender', models.CharField(max_length=3, validators=[schedule.validate.valid_gender], verbose_name='子供の性別')),
                ('barth_date', models.DateTimeField(null=True, verbose_name='子供の生年月日')),
                ('hobby', models.TextField(blank=True, null=True, verbose_name='好きな遊び')),
                ('character', models.TextField(blank=True, null=True, verbose_name='好きなキャラクター')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Children',
            },
        ),
    ]
