# Generated by Django 3.0 on 2020-01-01 01:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200101_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='period',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.AddField(
            model_name='schedule',
            name='periods',
            field=models.IntegerField(choices=[(0, '午前'), (1, '正午'), (2, '午後')], default=0, verbose_name='時間帯'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='stats',
            field=models.IntegerField(choices=[(0, '●'), (1, '▲'), (2, '×')], default=1, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 1, 48, 35, 219489, tzinfo=utc), verbose_name='日付'),
        ),
    ]
