# Generated by Django 3.0 on 2020-01-01 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20200101_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 2, 6, 35, 984329, tzinfo=utc), verbose_name='日付'),
        ),
    ]
