# Generated by Django 3.0 on 2020-01-01 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20200101_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='periods',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 2, 9, 14, 871849, tzinfo=utc), verbose_name='日付'),
        ),
    ]
