# Generated by Django 3.0 on 2020-01-01 03:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20200101_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='period',
            field=models.IntegerField(choices=[(0, '午前'), (1, '正午'), (2, '午後')], default=0, verbose_name='時間帯'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='status',
            field=models.IntegerField(choices=[(0, '●'), (1, '▲'), (2, '×')], default=1, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 3, 2, 4, 323026, tzinfo=utc), verbose_name='日付'),
        ),
    ]
