# Generated by Django 3.0 on 2020-01-05 05:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0015_auto_20200101_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='name',
        ),
        migrations.AddField(
            model_name='friends',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='friend', to=settings.AUTH_USER_MODEL, verbose_name='友人'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 5, 5, 8, 55, 196258, tzinfo=utc), verbose_name='日付'),
        ),
    ]
